name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: Hello @${{ github.actor }}, thank you for your interest in my work! üëã
                      To get started, you need to have a Debian- or Ubuntu-based distribution of Linux with Bash as the default interactive shell.
                      Run the following commands
                        ```bash
                        $ cd ~
                        $ cp -i .bashrc bashrc.old
                        $ git clone https://github.com/TomfromBerlin/bashrc
                        $ cd bashrc
                        $ cp -iR .bashrc .shellcfg ~/
                        ```

                      The .bashrc file and associated files should be run in environments based on [Debian](https://www.debian.org/) and [Ubuntu](https://ubuntu.com/download)
                      It may not run on Fedora, FreeBSD, and other distributions!
                      There is abolutely no warranty.
                      
                      If this is a üêõ Bug Report, please provide screenshots and/or log entries and **minimum viable code to reproduce your issue**, otherwise I can not help you.
          
        pr-message: Hello @${{ github.actor }}, thank you for submitting a PR! üëã To allow your work to be integrated as seamlessly as possible, we advise you to
                  - ‚úÖ Verify your PR is **up-to-date with upstream/master.**
                  If your PR is behind upstream/master an automatic [GitHub actions](https://github.com/TomfromBerlin/bashrc/blob/master/.github/workflows/rebase.yml) rebase may be attempted by including the /rebase command in a comment body, or by running the following code, replacing 'feature' with the name of your local branch
                    ```bash
                    git remote add upstream https://github.com/TomfromBerlin/bashrc.git
                    git fetch upstream
                    git checkout feature  <----- replace 'feature' with local branch name
                    git merge upstream/master
                    git push -u origin
                    ```
                  - ‚úÖ Verify all Continuous Integration (CI) **checks are passing**.
                  - ‚úÖ Reduce changes to the absolute **minimum** required for your bug fix or feature addition.
